# .travis.yml Execution script for role tests on Travis-CI
---
sudo: required

env:
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7
    - DISTRIBUTION: ubuntu
      VERSION: 16.04
    - DISTRIBUTION: debian
      VERSION: 9

services:
  - docker

before_install:
  # Install latest Git
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git
  # Allow fetching other branches than master
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  # Fetch the branch with test code
  - git fetch origin docker-tests
  - git worktree add docker-tests origin/docker-tests
  # Lint
  - pip install --upgrade pip
  - pip install ansible-lint yamllint

script:
  # Lint
  - ansible-lint .
  - yamllint .

  # Create container and apply test playbook
  - ./docker-tests/docker-tests.sh

  # Run functional tests on the container
  - SUT_ID=$(docker ps -qa) ./docker-tests/functional-tests.sh
...
