---
# Test playbook for Ansible role cdelgehier.openio-repository

- hosts: all
  gather_facts: true
  become: true

  # Remove "universe" repository to check if the role properly re-enables it
  pre_tasks:
    - name: 'Install software-properties-common'
      command: 'apt-get install -y software-properties-common'
      changed_when: false

    - name: 'Ensure universe repository is not enabled/defined'
      command: 'add-apt-repository -r universe'
      changed_when: false

    - name: 'Remove software-properties-common, as the role will do that, which should also be tested'
      command: 'apt-get purge -y software-properties-common'
      changed_when: false

    - name: 'Update repositories metadata'
      command: 'apt-get update'
      changed_when: false

  roles:
    - role: role_under_test

    - role: role_under_test
      openio_repository_products:
        sds:
          release: "16.10"
      when: ansible_distribution != 'Debian'

    - role: role_under_test
      openio_repository_products:
        test:
          release: '17.04'
          password: 'bar'
          user: 'foo'

...
