---
# Test playbook for Ansible role cdelgehier.openio-repository

- hosts: all
  gather_facts: true
  become: true

  roles:
    - role: role_under_test

    - role: role_under_test
      openio_repository_products:
        sds:
          release: "16.10"
      when: ansible_distribution != 'Debian'

    - role: role_under_test
      openio_repository_products:
        test:
          release: '17.04'
          password: 'bar'
          user: 'foo'

...
