---
- name: Ensure lsb-release package is installed
  package:
    name: "lsb-release"
    state: present
  register: lsbrelease

- name: "Refetch facts"
  setup:
  when: lsbrelease.changed

- name: "Configure Backports repository for {{ ansible_lsb.id }} {{ ansible_distribution_release }}"
  apt_repository:
    repo: "deb http://httpredir.debian.org/debian/ {{ ansible_distribution_release }}-backports main contrib non-free"
    state: present
    filename: "{{ ansible_distribution_release }}-backports"
  when: ansible_lsb.id == 'Debian'

- name: "Setup repository key"
  apt_key:
    id: "{{ openio_repository_keyid }}"
    url: "{{ openio_repository_url }}/{{ openio_repository_gpgkey }}"
    state: present

- name: "Configure {{ openio_repository_product }} repository for {{ ansible_lsb.id }} {{ ansible_distribution_release }}"
  apt_repository:
    repo: "{{ openio_repository_baseurl }}"
    state: present
    filename: "openio-{{ openio_repository_product }}-{{ openio_repository_release }}"

- name: "Update APT cache"
  apt:
    update_cache: yes
  changed_when: false

- name: Configure policy to disable starting services at package install
  copy:
    src: policy-rc.d
    dest: /usr/sbin/policy-rc.d
    owner: root
    group: root
    mode: 0755
  when:
    - openio_repository_disable_policy_autostart
...
