---
- name: "Setup the repository key"
  rpm_key:
    state: present
    key: "{{ openio_repository_url }}/{{ openio_repository_gpgkey }}"

- name: "Configure {{ openio_repository_product }} repository for {{ ansible_distribution}} {{ ansible_distribution_major_version }}"
  yum_repository:
    name: "openio-{{ openio_repository_product }}-{{ openio_repository_distribution }}"
    description: "OpenIO {{ openio_repository_product }} {{ openio_repository_distribution }} packages for Entreprise Linux $releasever - $basearch"
    file: "openio-{{ openio_repository_product }}-{{ openio_repository_distribution }}"
    baseurl: "{{ openio_repository_baseurl }}/el/$releasever/$basearch"
    enabled: yes
    gpgcheck: yes

- name: "Configure {{ openio_repository_product }} source repository for {{ ansible_distribution}} {{ ansible_distribution_major_version }}"
  yum_repository:
    name: "openio-{{ openio_repository_product }}-{{ openio_repository_distribution }}-source"
    description: "OpenIO {{ openio_repository_product }} {{ openio_repository_distribution }} packages for Entreprise Linux $releasever - $basearch - Source"
    file: "openio-{{ openio_repository_product }}-{{ openio_repository_distribution }}"
    baseurl: "{{ openio_repository_baseurl }}/el/$releasever/SRPM"
    enabled: no
    gpgcheck: yes
...
