---
- name: "Configure {{ openio_repository_product }} repository for {{ ansible_lsb.id }} {{ ansible_distribution_release }}"
  apt_repository:
    repo: "{{ openio_repository_baseurl }}"
    state: absent
    filename: "openio-{{ openio_repository_product }}-{{ openio_repository_release }}"

- name: "Update APT cache"
  apt:
    update_cache: yes
  changed_when: false
...
